Resources
{
	"materials/hud/leaderboard_class_demo_backbreaker.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vtf"	"file"
	"materials/hud/leaderboard_class_demo_targe_nys.vmt"	"file"
	"materials/hud/leaderboard_class_demo_targe_nys.vtf"	"file"
	"materials/hud/leaderboard_class_demo_targe_nys_giant.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_heater_nys.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_heater_nys.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_heater_nys_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz_armored.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz_armored.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_quickfix_armored.vmt"	"file"
	"materials/hud/leaderboard_class_medic_quickfix_armored.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_neon.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_neon.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_neon_giant.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_scorch.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_scorch.vtf"	"file"
	"materials/hud/leaderboard_class_scout_stun_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vtf"	"file"
	"materials/hud/leaderboard_class_spy_enforcer_nys.vmt"	"file"
	"materials/hud/leaderboard_class_spy_enforcer_nys.vtf"	"file"
	"materials/hud/leaderboard_class_spy_enforcer_nys_giant.vmt"	"file"
}
