Resources
{
	"materials/hud/leaderboard_class_demo_caber_nys.vmt"	"file"
	"materials/hud/leaderboard_class_demo_caber_nys.vtf"	"file"
	"materials/hud/leaderboard_class_demo_chief_loosecannon.vmt"	"file"
	"materials/hud/leaderboard_class_demo_chief_loosecannon.vtf"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vtf"	"file"
	"materials/hud/leaderboard_class_demo_sticky_daan.vmt"	"file"
	"materials/hud/leaderboard_class_demo_sticky_daan.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_brass_nys.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_brass_nys.vtf"	"file"
	"materials/hud/leaderboard_class_medic_blast.vmt"	"file"
	"materials/hud/leaderboard_class_medic_blast.vtf"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vmt"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vtf"	"file"
	"materials/hud/leaderboard_class_medic_fire.vmt"	"file"
	"materials/hud/leaderboard_class_medic_fire.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_uber.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_uber.vtf"	"file"
	"materials/hud/leaderboard_class_medic_vac_trio_nys.vmt"	"file"
	"materials/hud/leaderboard_class_medic_vac_trio_nys.vtf"	"file"
	"materials/hud/leaderboard_class_scout_milk.vmt"	"file"
	"materials/hud/leaderboard_class_scout_milk.vtf"	"file"
	"materials/hud/leaderboard_class_scout_stun_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_blast.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_blast.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_escape.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_escape.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_libertylauncher_crit.vmt"	"file"
}
