Resources
{
	"materials/hud/leaderboard_class_demo_skullcutter.vmt"	"file"
	"materials/hud/leaderboard_class_demo_skullcutter.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_healonkill.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_healonkill.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_caustic.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_caustic.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_dragon_fury_swordstone.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_dragon_fury_swordstone.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_fireaxe.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_fireaxe.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_manmelter.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_manmelter.vtf"	"file"
	"materials/hud/leaderboard_class_scout_bostonbasher.vmt"	"file"
	"materials/hud/leaderboard_class_scout_bostonbasher.vtf"	"file"
	"materials/hud/leaderboard_class_scout_stun_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_bow_bleed.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_bow_bleed.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_airstrike.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_airstrike.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_equalizer.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_equalizer.vtf"	"file"
}
