Resources
{
	"materials/hud/leaderboard_class_boss_hatman.vmt"	"file"
	"materials/hud/leaderboard_class_boss_hatman.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_deflector_push_giant.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_natascha_nys.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_natascha_nys.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vtf"	"file"
	"materials/hud/leaderboard_class_scout_cola.vmt"	"file"
	"materials/hud/leaderboard_class_scout_cola.vtf"	"file"
	"materials/hud/leaderboard_class_scout_stun_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_bushwacka.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_bushwacka.vtf"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_crits.vmt"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_crits.vtf"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_ghosts.vmt"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_ghosts.vtf"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_gravity.vmt"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_gravity.vtf"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_jarate.vmt"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_jarate.vtf"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_superspeed.vmt"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_superspeed.vtf"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_uber.vmt"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_uber.vtf"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_whammy.vmt"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_whammy.vtf"	"file"
}
