Resources
{
	"materials/hud/leaderboard_class_Medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_demo_spammer.vmt"	"file"
	"materials/hud/leaderboard_class_demo_spammer.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_brassbeast.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_brassbeast.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_deflector_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_blast.vmt"	"file"
	"materials/hud/leaderboard_class_medic_blast.vtf"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vmt"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_dragon_fury_swordstone.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_dragon_fury_swordstone.vtf"	"file"
	"materials/hud/leaderboard_class_scout_cleaver.vmt"	"file"
	"materials/hud/leaderboard_class_scout_cleaver.vtf"	"file"
	"materials/hud/leaderboard_class_scout_fanowar.vmt"	"file"
	"materials/hud/leaderboard_class_scout_fanowar.vtf"	"file"
	"materials/hud/leaderboard_class_scout_stun_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vtf"	"file"
}
