Resources
{
	"materials/hud/leaderboard_class_demo_cannon.vmt"	"file"
	"materials/hud/leaderboard_class_demo_cannon.vtf"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb.vmt"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_dragon_fury_swordstone.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_dragon_fury_swordstone.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_flare_rainer.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_flare_rainer_giant.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_manmelter.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_manmelter.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_phlog.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_phlog.vtf"	"file"
	"materials/hud/leaderboard_class_scout_milk.vmt"	"file"
	"materials/hud/leaderboard_class_scout_milk.vtf"	"file"
	"materials/hud/leaderboard_class_scout_pistol_moon.vmt"	"file"
	"materials/hud/leaderboard_class_scout_pistol_moon.vtf"	"file"
	"materials/hud/leaderboard_class_scout_stun_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_backup_spammer.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_backup_spammer_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_buff_spammer.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_buff_spammer.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_burstfire_backup.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_burstfire_backup.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_nuker.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_nuker_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_rocketrain.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_rocketrain_giant.vmt"	"file"
}
