Resources
{
	"materials/hud/leaderboard_class_demo_spammer.vmt"	"file"
	"materials/hud/leaderboard_class_demo_spammer.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_booster.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_booster.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_deflector_fire.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_deflector_fire.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_heater_nys.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_heater_nys.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vtf"	"file"
	"materials/hud/leaderboard_class_medic_uber_giant.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_phlog.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_phlog.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_scorch.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_scorch.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_slowdown.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_slowdown.vtf"	"file"
	"materials/hud/leaderboard_class_scout_fan_armored.vmt"	"file"
	"materials/hud/leaderboard_class_scout_fan_armored.vtf"	"file"
	"materials/hud/leaderboard_class_scout_fanowar.vmt"	"file"
	"materials/hud/leaderboard_class_scout_fanowar.vtf"	"file"
	"materials/hud/leaderboard_class_scout_stun_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_smg.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_smg.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_heal.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_heal.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_infinite.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_infinite.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_directhit.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_directhit.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_mangler.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_mangler.vtf"	"file"
}
