//Calendartillery PointTemplate file
//Dependency: popextensions_main.nut
//Generated by the Potato.tf PointTemplate converter
::PointTemplates <- 
{
	FakeParent = 
	{
		NoFixup = 1,
		[0] =
		{
			info_target =
			{
				targetname = "grand_dad_of_the_general"
			}
		},
	}
	TheGeneralsDefeat = 
	{
		NoFixup = 1,
		[0] =
		{
			prop_dynamic =
			{
				targetname = "heavy_model_prop_defeat"
				origin = "0,0,0"
				model = "models/player/heavy.mdl"
				skin = "1"
				modelscale = 1.75
				defaultanim = "tauntrussian_rubdown"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[1] =
		{
			prop_dynamic_ornament =
			{
				targetname = "heavy_model_prop_defeat_ornaments"
				InitialOwner = "heavy_model_prop_defeat"
				model = "models/player/items/all_class/wikicap_heavy.mdl"
				skin = "1"
				spawnflags = "256"
				DisableBoneFollowers = "1"
				disableshadows = "1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[2] =
		{
			prop_dynamic_ornament =
			{
				targetname = "heavy_model_prop_defeat_ornaments"
				InitialOwner = "heavy_model_prop_defeat"
				model = "models/workshop/player/items/all_class/fall2013_the_cuban_coverup/fall2013_the_cuban_coverup_heavy.mdl"
				spawnflags = "256"
				DisableBoneFollowers = "1"
				disableshadows = "1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[3] =
		{
			prop_dynamic_ornament =
			{
				targetname = "heavy_model_prop_defeat_ornaments"
				InitialOwner = "heavy_model_prop_defeat"
				model = "models/workshop/player/items/heavy/cc_summer2015_commissars_coat/cc_summer2015_commissars_coat.mdl"
				skin = "1"
				spawnflags = "256"
				DisableBoneFollowers = "1"
				disableshadows = "1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[4] =
		{
			prop_dynamic_ornament =
			{
				targetname = "heavy_model_prop_defeat_ornaments"
				InitialOwner = "heavy_model_prop_defeat"
				model = "models/weapons/c_models/c_minigun/c_minigun.mdl"
				skin = "1"
				spawnflags = "256"
				DisableBoneFollowers = "1"
				disableshadows = "1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[5] =
		{
			info_particle_system =
			{
				targetname = "prize_particle",
				effect_name = "utaunt_arcane_yellow_parent",
				start_active = "1",
			}
		},
	},
	TheGeneralsDefeatHint = 
	{
		NoFixup = 1,
		[0] =
		{
			training_annotation =
			{
				targetname = "prize_hint",
				display_text = "Honor The General's wish by picking up the Golden Pan!",
				lifetime = "8",
			}
		},
		[1] =
		{
			OnSpawnOutput = {
				Target = "prize_hint",
				Action = "Show",
				Delay = 1,
			}
		},
	},
	TheGeneralsBuffs =
	{
		[0] =
		{
			trigger_add_tf_player_condition =
			{
				targetname = "general_buff_trigger"
				mins = Vector(-300,-300,-300)
				maxs = Vector(300,300,300)
				filtername = "filter_bluteam"
				spawnflags = 64
				condition = 16
				duration = -1
			}
		},
		[1] =
		{
			trigger_add_tf_player_condition =
			{
				targetname = "general_buff_trigger"
				mins = Vector(-300,-300,-300)
				maxs = Vector(300,300,300)
				filtername = "filter_bluteam"
				spawnflags = 64
				condition = 42
				duration = -1
			}
		},
		[2] =
		{
			info_particle_system =
			{
				targetname = "general_buff_particle"
				effect_name = "medic_resist_fire"
				start_active = 1
			}
		},
	}
	TheGeneralsCar = 
	{
		NoFixup = 1,
		[0] =
		{
			prop_dynamic =
			{
				targetname = "heavy_model_prop"
				origin = "0,0,0"
				model = "models/player/heavy.mdl"
				skin = "1"
				modelscale = 1.75
				defaultanim = "taunt_the_road_rager_a1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[1] =
		{
			prop_dynamic_ornament =
			{
				targetname = "heavy_model_prop_ornaments"
				InitialOwner = "heavy_model_prop"
				model = "models/player/items/all_class/wikicap_heavy.mdl"
				skin = "1"
				spawnflags = "256"
				DisableBoneFollowers = "1"
				disableshadows = "1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[2] =
		{
			prop_dynamic_ornament =
			{
				targetname = "heavy_model_prop_ornaments"
				InitialOwner = "heavy_model_prop"
				model = "models/workshop/player/items/all_class/fall2013_the_cuban_coverup/fall2013_the_cuban_coverup_heavy.mdl"
				spawnflags = "256"
				DisableBoneFollowers = "1"
				disableshadows = "1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[3] =
		{
			prop_dynamic_ornament =
			{
				targetname = "heavy_model_prop_ornaments"
				InitialOwner = "heavy_model_prop"
				model = "models/workshop/player/items/heavy/cc_summer2015_commissars_coat/cc_summer2015_commissars_coat.mdl"
				skin = "1"
				spawnflags = "256"
				DisableBoneFollowers = "1"
				disableshadows = "1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[4] =
		{
			prop_dynamic_ornament =
			{
				targetname = "heavy_model_prop_ornaments"
				InitialOwner = "heavy_model_prop"
				model = "models/workshop/player/items/heavy/road_rager/road_rager.mdl"
				skin = "1"
				spawnflags = "256"
				DisableBoneFollowers = "1"
				disableshadows = "1"
				solid = "0"
				rendermode = "0"
				renderfx = "0"
				renderamt = "255"
			}
		},
		[5] =
		{
			tf_point_weapon_mimic =
			{
				targetname = "heavy_shooter"
				// parentname = "heavy_model_prop"
				//X+ = in front, Y+ = left, Z+ = up(?)
				origin = "0 0 0"
				angles = "0 0 0"
				Crits = "0"
				Damage = 135 //+50%
				SpeedMax = 770
				SpeedMin = 770
				SplashRadius = 144
				SpreadAngle = 6
				WeaponType = 0
			}
		},
	},
	RotatingNeonSign = 
	{
		[0] =
		{
			prop_dynamic =
			{
				targetname = "neon_prop"
				parentname = "rot"
				model = "models/workshop_partner/weapons/c_models/c_sd_neonsign/c_sd_neonsign.mdl"
				skin = "1"
				origin = "0 0 0"
				angles = "90 0 0"
				modelscale = 0.8
			}
		},
		[1] =
		{
			OnParentKilledOutput = {
				Target = "!self"
				Action = "Kill"
				Delay = 0
			}
		},
		// [1] =
		// {
			// func_rotating =
			// {
				// targetname = "rot"
				// origin = "0 0 0"
				// spawnflags = 73 //not solid, spin on Y, start active
				// fanfriction = 100
				// maxspeed = 400
			// }
		// },
	},
	ProjectileShieldHint = 
	{
		[0] =
		{
			training_annotation =
			{
				targetname = "projshield_hint",
				display_text = "Shoot the Shield to break it!",
				lifetime = "5",
			}
		},
		[1] =
		{
			OnSpawnOutput = {
				Target = "projshield_hint",
				Action = "Show",
				Delay = 0.1,
			}
		},
	}
	SpiderProp =
	{
		[0] =
		{
			prop_dynamic =
			{
				targetname = "spider_prop_pet",
				origin = "0 0 5",
				model = "models/props_halloween/smlprop_spider.mdl",
				modelscale = 1.25,
				DisableBoneFollowers = 1,
			},
		},
	}
	//A Spider tank that bleeds on contact and shoots spider webs. Currently crashes, temporarily scrapped.
	//Original by...who, anyway? Was it asd, Force, or rafradek?
	PT_SpiderTank =
	{
		[0] =
		{
			trigger_multiple =
			{
				targetname = "turretSpider_hurt",
				origin = "7 4 108",
				mins = "-148 -94 -100",
				maxs = "148 94 100",
				filtername = "filter_red",
				spawnflags = 1,
				wait = 0,
				"OnStartTouch#1" : "!activator,BleedPlayer,3,0,-1",
				"OnStartTouchAll#1" : "!self,Disable,,1,-1",
				"OnStartTouchAll#2" : "!self,Enable,,1.01,-1",
			},
		},
		[1] =
		{
			trigger_multiple =
			{
				targetname = "turretSpider_dir_range",
				filtername = "filter_red",
				origin = "484 0 176",
				mins = "-624 -606 -280",
				maxs = "624 606 280",
				solid = 1,
				spawnflags = 1,
				wait = 1,
				"OnStartTouchAll#1" : "turretSpider_trackdir,SetParent,!activator,0.01,-1",
				"OnStartTouchAll#2" : "turretSpider_trackdir,SetParentAttachment,eyeglow_L,0.02,-1",
				"OnEndTouch#1" : "!self,Disable,,0,-1",
				"OnEndTouch#2" : "turretSpider_trackdir,ClearParent,,0,-1",
				"OnEndTouch#3" : "!self,Enable,,0.01,-1",
			},
		},
		[2] =
		{
			path_track =
			{
				targetname = "turretSpider_trackdir",
				origin = "-139 -11.001 51.755",
				orientationtype = 1,
				speed = 0,
			},
		},
		[3] =
		{
			info_target =
			{
				targetname = "turretSpider_projected",
				origin = "44 -6.001 199.999",
			},
		},
		[4] =
		{
			logic_timer =
			{
				targetname = "turretSpider_firetimer",
				RefireTime = 0.35,
				"OnTimer#1" : "turretSpider_firerelay,Trigger,,0,-1",
			},
		},
		[5] =
		{
			logic_relay =
			{
				targetname = "turretSpider_firerelay",
				"OnTrigger#1" : "!self,Disable,,0,-1",
				// "OnTrigger#2" : "turretSpider_jaratemaker,ForceSpawn,,0.02,-1",
				"OnTrigger#3" : "turretSpider_jaratemaker_static,ForceSpawn,,0.02,-1",
				"OnTrigger#4" : "turretSpider_dir_range,DisableAndEndTouch,,0.5,-1",
				"OnTrigger#5" : "turretSpider_dir_range,Enable,,0.51,-1",
				"OnTrigger#6" : "!self,Enable,,4.2,-1",
			},
		},
		// [6] =
		// {
			// env_entity_maker =
			// {
				// targetname = "turretSpider_jaratemaker",
				// origin = "127 -1.242 168",
				// parentname = "turretSpider_projected",
				// EntityTemplate = "turretSpider_jaratetemp",
				// PostSpawnDirection = "-15 0 0",
				// PostSpawnDirectionVariance = 0,
				// PostSpawnInheritAngles = 1,
				// PostSpawnSpeed = 1000,
			// },
		// },
		[7] =
		{
			env_entity_maker =
			{
				targetname = "turretSpider_jaratemaker_static",
				origin = "107 42 136",
				EntityTemplate = "turretSpider_jaratetemp",
				PostSpawnDirection = "-30 8 0",
				PostSpawnDirectionVariance = 0,
				PostSpawnInheritAngles = 1,
				PostSpawnSpeed = 500,
			},
		},
		[8] =
		{
			env_entity_maker =
			{
				targetname = "turretSpider_jaratemaker_static",
				origin = "107 -42 136",
				angles = "-20 -20 0",
				EntityTemplate = "turretSpider_jaratetemp",
				PostSpawnDirection = "-30 -8 0",
				PostSpawnDirectionVariance = 0,
				PostSpawnInheritAngles = 1,
				PostSpawnSpeed = 500,
			},
		},
		// [9] =
		// {
			// prop_dynamic =
			// {
				// model = "models/bots/boss_bot/boss_tank.mdl",
				// origin = "-1 2 4",
				// angles = "0 0 0",
				// skin = 0,
			// },
		// },
		// [10] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_prop",
				// parentname = "turretSpider_projected",
				// origin = "43 -6 168",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 7,
				// DisableBoneFollowers = 1,
			// },
		// },
		// [11] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "23 18 164",
				// angles = "0 15 0",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [12] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-1 -10 164",
				// angles = "0 0 0",
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
			// },
		// },
		// [13] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "39 42 112",
				// angles = "-30 180 90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [14] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "67 42 140",
				// angles = "-75 0 90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [15] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "19 42 140",
				// angles = "-15 0 -90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [16] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-5 42 108",
				// angles = "30 0 -90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [17] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-49 42 132",
				// angles = "30 0 -90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [18] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-61 42 96",
				// angles = "-30 0 -90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [19] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "99 18 144",
				// angles = "30.1064 86.2486 93.7514",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [20] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "95 -14 124",
				// angles = "-45.0674 274.597 -87.6224",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [21] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "7 -38 140",
				// angles = "-90 90 0",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [22] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "71 -38 148",
				// angles = "-30 0 90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [23] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-45 -38 136",
				// angles = "0 0 90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [24] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-25 -38 92",
				// angles = "60 0 90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [25] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "55 -38 120",
				// angles = "30 0 90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 4,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [26] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-85 -14 128",
				// angles = "-60 96.5 -90",
				// model = "models/props_halloween/smlprop_spider.mdl",
				// modelscale = 5,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [27] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-13 42 108",
				// angles = "0 90 -90",
				// model = "models/props_halloween/cobweb_01.mdl",
				// modelscale = 1.5,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [28] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "55 42 128",
				// angles = "0 90 135",
				// model = "models/props_halloween/cobweb_01.mdl",
				// modelscale = 1,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [29] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "-9 -38 128",
				// angles = "0 270 90",
				// model = "models/props_halloween/cobweb_01.mdl",
				// modelscale = 1.5,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
		// [30] =
		// {
			// prop_dynamic =
			// {
				// targetname = "turretSpider_propglobal",
				// origin = "59 -38 120",
				// angles = "0 270 -30",
				// model = "models/props_halloween/cobweb_01.mdl",
				// modelscale = 1,
				// DisableBoneFollowers = 1,
				// disableshadows = 1,
			// },
		// },
	},
	turretSpider_jaratetemp =
	{
		NoFixup = 1,
		[0] =
		{
			logic_relay =
			{
				targetname = "turretSpider_webrelay",
				"OnSpawn#1" : "turretSpider_webphys,Kill,,14,-1",
			},
		},
		[1] =
		{
			trigger_stun =
			{
				targetname = "turretSpider_webslow",
				parentname = "turretSpider_webphys",
				origin = "15 2 -8",
				mins = "-28 -28 -28",
				maxs = "28 28 28",
				filtername = "filter_red",
				spawnflags = 1,
				stun_type = 0,
				move_speed_reduction = 0.5,
				stun_duration = 0.5,
				trigger_delay = 0,
			},
		},
		[2] =
		{
			prop_physics_override =
			{
				targetname = "turretSpider_webphys",
				origin = "15 2 -24",
				model = "models/props_2fort/miningcrate002.mdl",
				disableshadows = 1,
				inertiaScale = 999,
				rendermode = 10,
				solid = 0,
				spawnflags = 8452,
				effects = 32,
				"OnAwakened#1" : "turretSpider_webphys,SetMass,10,0,-1",
			},
		},
		[3] =
		{
			filter_activator_team =
			{
				targetname = "filter_red",
				filterteam = 2,
			},
		},
		[4] =
		{
			prop_dynamic =
			{
				targetname = "turretSpider_webprop",
				parentname = "turretSpider_webphys",
				origin = "19 -6 0",
				angles = "30 90 90",
				model = "models/props_halloween/cobweb_01.mdl",
				spawnflags = 256,
				disableshadows = 1,
			},
		},
		[5] =
		{
			prop_dynamic =
			{
				targetname = "turretSpider_webprop",
				parentname = "turretSpider_webphys",
				origin = "19 -6 -8",
				angles = "0 60 0",
				model = "models/props_halloween/cobweb_01.mdl",
				spawnflags = 256,
				disableshadows = 1,
			},
		},
		[6] =
		{
			prop_dynamic =
			{
				targetname = "turretSpider_webprop",
				parentname = "turretSpider_webphys",
				origin = "23 -6 -8",
				angles = "0 285 0",
				model = "models/props_halloween/cobweb_01.mdl",
				spawnflags = 256,
				disableshadows = 1,
			},
		},
		[7] =
		{
			prop_dynamic =
			{
				targetname = "turretSpider_webprop",
				parentname = "turretSpider_webphys",
				origin = "35 6 8",
				angles = "0 120 180",
				model = "models/props_halloween/cobweb_01.mdl",
				spawnflags = 256,
				disableshadows = 1,
			},
		},
		[8] =
		{
			prop_dynamic =
			{
				targetname = "turretSpider_webprop",
				parentname = "turretSpider_webphys",
				origin = "23 -2 -8",
				angles = "0 195 0",
				model = "models/props_halloween/cobweb_01.mdl",
				spawnflags = 256,
				disableshadows = 1,
			},
		},
		[9] =
		{
			prop_dynamic =
			{
				targetname = "turretSpider_webprop",
				parentname = "turretSpider_webphys",
				origin = "27 -2 0",
				angles = "0 15 -180",
				model = "models/props_halloween/cobweb_01.mdl",
				disableshadows = 1,
				spawnflags = 256,
			},
		},
		[10] =
		{
			prop_dynamic =
			{
				targetname = "turretSpider_webprop",
				parentname = "turretSpider_webphys",
				origin = "23 2 -24",
				model = "models/props_halloween/smlprop_spider.mdl",
				DisableBoneFollowers = 1,
				disableshadows = 1,
			},
		},
	},
}